### ISSUE TITLE
我npm run build后，打包出来的域名是七牛的测试域名，不是我配置里面填写的域名

### ISSUE THREAD

**Issue by amwihtfei** [zzetao/qiniu-webpack-plugin#2]
我npm run build后，打包出来的域名是七牛的测试域名，不是我配置里面填写的域名；这个是个什么情况？

**Comment by amwihtfei** [comment]
![image](https://user-images.githubusercontent.com/3423442/49065558-4f39cf80-f259-11e8-88bd-45e71b1cf967.png)
如图

**Comment by zzetao** [comment]
请检查一下 webpack 是否有用了其他相关插件导致的域名不一致
